In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [25]:
ls

 BL-Flickr-Images-Book.csv   hw1.ipynb      olympics.gsheet  'train .txt.csv'
 heart.csv                   olympics.csv   olympics.ipynb   'Week 3 - olympics.ipynb'

In [26]:
import numpy as np
import pandas as pd

In [10]:
df= pd.read_csv('olympics.csv',header=1)
df.head()

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [21]:
df.shape

(147, 16)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         147 non-null    object
 1   Summer          147 non-null    int64
 2   Gold_s          147 non-null    int64
 3   Silver_s        147 non-null    int64
 4   Bronze_s        147 non-null    int64
 5   Total_summer    147 non-null    int64
 6   Winter          147 non-null    int64
 7   Gold_w          147 non-null    int64
 8   Silver_w        147 non-null    int64
 9   Bronze_w        147 non-null    int64
 10  Total_Winter    147 non-null    int64
 11  Total_games     147 non-null    int64
 12  Tot_Gold        147 non-null    int64
 13  Tol_Sil         147 non-null    int64
 14  Tol_Bro         147 non-null    int64
 15  Combined_total  147 non-null    int64
dtypes: int64(15), object(1)
memory usage: 18.5+ KB

In [33]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.rename(columns={'Unnamed: 0': 'Country', '? Summer': 'Summer', '01 !': 'Gold_s','02 !':'Silver_s','03 !':'Bronze_s','Total':'Total_summer','? Winter':'Winter','01 !.1':'Gold_w','02 !.1':'Silver_w','03 !.1':'Bronze_w','Total.1':'Total_Winter','? Games':'Total_games','01 !.2':'Tot_Gold','02 !.2':'Tol_Sil','03 !.2':'Tol_Bro','Combined total':'Combined_total'}, inplace=True)

In [34]:
df.head()

,Country,Summer,Gold_s,Silver_s,Bronze_s,Total_summer,Winter,Gold_w,Silver_w,Bronze_w,Total_Winter,Total_games,Tot_Gold,Tol_Sil,Tol_Bro,Combined_total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [13]:
data_types = df.dtypes
print(data_types)

Country           object
Summer             int64
Gold_s             int64
Silver_s           int64
Bronze_s           int64
Total_summer       int64
Winter             int64
Gold_w             int64
Silver_w           int64
Bronze_w           int64
Total_Winter       int64
Total_games        int64
Tot_Gold           int64
Tol_Sil            int64
Tol_Bro            int64
Combined_total     int64
dtype: object

In [14]:
duplicate_rows=df.duplicated()
df.duplicated().sum()

0

In [36]:
df.isnull()

,Country,Summer,Gold_s,Silver_s,Bronze_s,Total_summer,Winter,Gold_w,Silver_w,Bronze_w,Total_Winter,Total_games,Tot_Gold,Tol_Sil,Tol_Bro,Combined_total
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
143,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
144,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
145,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
146,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [37]:
df.isnull().sum()

Country           0
Summer            0
Gold_s            0
Silver_s          0
Bronze_s          0
Total_summer      0
Winter            0
Gold_w            0
Silver_w          0
Bronze_w          0
Total_Winter      0
Total_games       0
Tot_Gold          0
Tol_Sil           0
Tol_Bro           0
Combined_total    0
dtype: int64

In [17]:
df.describe()

,Summer,Gold_s,Silver_s,Bronze_s,Total_summer,Winter,Gold_w,Silver_w,Bronze_w,Total_Winter,Total_games,Tot_Gold,Tol_Sil,Tol_Bro,Combined_total
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,13.476190,65.428571,64.965986,69.795918,200.190476,6.700680,13.047619,13.034014,12.897959,38.979592,20.176871,78.476190,78.000000,82.693878,239.170068
std,7.072359,405.549990,399.309960,427.187344,1231.306297,7.433186,80.799204,80.634421,79.588388,240.917324,13.257048,485.013378,478.860334,505.855110,1469.067883
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.000000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,1.000000,1.000000,2.500000
50%,13.000000,3.000000,4.000000,6.000000,12.000000,5.000000,0.000000,0.000000,0.000000,0.000000,15.000000,3.000000,4.000000,7.000000,12.000000
75%,18.500000,24.000000,28.000000,29.000000,86.000000,10.000000,1.000000,2.000000,1.000000,5.000000,27.000000,25.500000,29.000000,32.500000,89.000000
max,27.000000,4809.000000,4775.000000,5130.000000,14714.000000,22.000000,959.000000,958.000000,948.000000,2865.000000,49.000000,5768.000000,5733.000000,6078.000000,17579.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         147 non-null    object
 1   Summer          147 non-null    int64
 2   Gold_s          147 non-null    int64
 3   Silver_s        147 non-null    int64
 4   Bronze_s        147 non-null    int64
 5   Total_summer    147 non-null    int64
 6   Winter          147 non-null    int64
 7   Gold_w          147 non-null    int64
 8   Silver_w        147 non-null    int64
 9   Bronze_w        147 non-null    int64
 10  Total_Winter    147 non-null    int64
 11  Total_games     147 non-null    int64
 12  Tot_Gold        147 non-null    int64
 13  Tol_Sil         147 non-null    int64
 14  Tol_Bro         147 non-null    int64
 15  Combined_total  147 non-null    int64
dtypes: int64(15), object(1)
memory usage: 18.5+ KB

In [19]:
df.loc[~df['Country'].astype(str).str.isdigit(), 'Country'].tolist()

['Afghanistan (AFG)',
 'Algeria (ALG)',
 'Argentina (ARG)',
 'Armenia (ARM)',
 'Australasia (ANZ) [ANZ]',
 'Australia (AUS) [AUS] [Z]',
 'Austria (AUT)',
 'Azerbaijan (AZE)',
 'Bahamas (BAH)',
 'Bahrain (BRN)',
 'Barbados (BAR) [BAR]',
 'Belarus (BLR)',
 'Belgium (BEL)',
 'Bermuda (BER)',
 'Bohemia (BOH) [BOH] [Z]',
 'Botswana (BOT)',
 'Brazil (BRA)',
 'British West Indies (BWI) [BWI]',
 'Bulgaria (BUL) [H]',
 'Burundi (BDI)',
 'Cameroon (CMR)',
 'Canada (CAN)',
 'Chile (CHI) [I]',
 'China (CHN) [CHN]',
 'Colombia (COL)',
 'Costa Rica (CRC)',
 'Ivory Coast (CIV) [CIV]',
 'Croatia (CRO)',
 'Cuba (CUB) [Z]',
 'Cyprus (CYP)',
 'Czech Republic (CZE) [CZE]',
 'Czechoslovakia (TCH) [TCH]',
 'Denmark (DEN) [Z]',
 'Djibouti (DJI) [B]',
 'Dominican Republic (DOM)',
 'Ecuador (ECU)',
 'Egypt (EGY) [EGY] [Z]',
 'Eritrea (ERI)',
 'Estonia (EST)',
 'Ethiopia (ETH)',
 'Finland (FIN)',
 'France (FRA) [O] [P] [Z]',
 'Gabon (GAB)',
 'Georgia (GEO)',
 'Germany (GER) [GER] [Z]',
 'United Team of Germany (EUA) [EUA]',
 'East Germany (GDR) [GDR]',
 'West Germany (FRG) [FRG]',
 'Ghana (GHA) [GHA]',
 'Great Britain (GBR) [GBR] [Z]',
 'Greece (GRE) [Z]',
 'Grenada (GRN)',
 'Guatemala (GUA)',
 'Guyana (GUY) [GUY]',
 'Haiti (HAI) [J]',
 'Hong Kong (HKG) [HKG]',
 'Hungary (HUN)',
 'Iceland (ISL)',
 'India (IND) [F]',
 'Indonesia (INA)',
 'Iran (IRI) [K]',
 'Iraq (IRQ)',
 'Ireland (IRL)',
 'Israel (ISR)',
 'Italy (ITA) [M] [S]',
 'Jamaica (JAM) [JAM]',
 'Japan (JPN)',
 'Kazakhstan (KAZ)',
 'Kenya (KEN)',
 'North Korea (PRK)',
 'South Korea (KOR)',
 'Kuwait (KUW)',
 'Kyrgyzstan (KGZ)',
 'Latvia (LAT)',
 'Lebanon (LIB)',
 'Liechtenstein (LIE)',
 'Lithuania (LTU)',
 'Luxembourg (LUX) [O]',
 'Macedonia (MKD)',
 'Malaysia (MAS) [MAS]',
 'Mauritius (MRI)',
 'Mexico (MEX)',
 'Moldova (MDA)',
 'Mongolia (MGL)',
 'Montenegro (MNE)',
 'Morocco (MAR)',
 'Mozambique (MOZ)',
 'Namibia (NAM)',
 'Netherlands (NED) [Z]',
 'Netherlands Antilles (AHO) [AHO] [I]',
 'New Zealand (NZL) [NZL]',
 'Niger (NIG)',
 'Nigeria (NGR)',
 'Norway (NOR) [Q]',
 'Pakistan (PAK)',
 'Panama (PAN)',
 'Paraguay (PAR)',
 'Peru (PER) [L]',
 'Philippines (PHI)',
 'Poland (POL)',
 'Portugal (POR)',
 'Puerto Rico (PUR)',
 'Qatar (QAT)',
 'Romania (ROU)',
 'Russia (RUS) [RUS]',
 'Russian Empire (RU1) [RU1]',
 'Soviet Union (URS) [URS]',
 'Unified Team (EUN) [EUN]',
 'Saudi Arabia (KSA)',
 'Senegal (SEN)',
 'Serbia (SRB) [SRB]',
 'Serbia and Montenegro (SCG) [SCG]',
 'Singapore (SIN)',
 'Slovakia (SVK) [SVK]',
 'Slovenia (SLO)',
 'South Africa (RSA)',
 'Spain (ESP) [Z]',
 'Sri Lanka (SRI) [SRI]',
 'Sudan (SUD)',
 'Suriname (SUR) [E]',
 'Sweden (SWE) [Z]',
 'Switzerland (SUI)',
 'Syria (SYR)',
 'Chinese Taipei (TPE) [TPE] [TPE2]',
 'Tajikistan (TJK)',
 'Tanzania (TAN) [TAN]',
 'Thailand (THA)',
 'Togo (TOG)',
 'Tonga (TGA)',
 'Trinidad and Tobago (TRI) [TRI]',
 'Tunisia (TUN)',
 'Turkey (TUR)',
 'Uganda (UGA)',
 'Ukraine (UKR)',
 'United Arab Emirates (UAE)',
 'United States (USA) [P] [Q] [R] [Z]',
 'Uruguay (URU)',
 'Uzbekistan (UZB)',
 'Venezuela (VEN)',
 'Vietnam (VIE)',
 'Virgin Islands (ISV)',
 'Yugoslavia (YUG) [YUG]',
 'Independent Olympic Participants (IOP) [IOP]',
 'Zambia (ZAM) [ZAM]',
 'Zimbabwe (ZIM) [ZIM]',
 'Mixed team (ZZX) [ZZX]',
 'Totals']

In [50]:
for i in df.select_dtypes(include="object").columns:
 print(df[i].value_counts())
 print('***'*10)

Country
Afghanistan (AFG)                1
Serbia (SRB) [SRB]               1
Pakistan (PAK)                   1
Panama (PAN)                     1
Paraguay (PAR)                   1
                                ..
Great Britain (GBR) [GBR] [Z]    1
Greece (GRE) [Z]                 1
Grenada (GRN)                    1
Guatemala (GUA)                  1
Totals                           1
Name: count, Length: 147, dtype: int64
******************************

In [40]:
df.describe().T

                count        mean          std  min   25%   50%   75%      max
Summer          147.0   13.476190     7.072359  1.0   8.0  13.0  18.5     27.0
Gold_s          147.0   65.428571   405.549990  0.0   0.0   3.0  24.0   4809.0
Silver_s        147.0   64.965986   399.309960  0.0   1.0   4.0  28.0   4775.0
Bronze_s        147.0   69.795918   427.187344  0.0   1.0   6.0  29.0   5130.0
Total_summer    147.0  200.190476  1231.306297  0.0   2.0  12.0  86.0  14714.0
Winter          147.0    6.700680     7.433186  0.0   0.0   5.0  10.0     22.0
Gold_w          147.0   13.047619    80.799204  0.0   0.0   0.0   1.0    959.0
Silver_w        147.0   13.034014    80.634421  0.0   0.0   0.0   2.0    958.0
Bronze_w        147.0   12.897959    79.588388  0.0   0.0   0.0   1.0    948.0
Total_Winter    147.0   38.979592   240.917324  0.0   0.0   0.0   5.0   2865.0
Total_games     147.0   20.176871    13.257048  1.0  11.0  15.0  27.0     49.0
Tot_Gold        147.0   78.476190   485.013378  0.0   0.0   3.0  25.5   5768.0
Tol_Sil         147.0   78.000000   478.860334  0.0   1.0   4.0  29.0   5733.0
Tol_Bro         147.0   82.693878   505.855110  0.0   1.0   7.0  32.5   6078.0
Combined_total  147.0  239.170068  1469.067883  1.0   2.5  12.0  89.0  17579.0

WARNING: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [41]:
df.describe(include="object").T

        count unique                top freq
Country   147    147  Afghanistan (AFG)    1